// Vue/src/App.vue
<script>
import Form from "./components/Form.vue";
import { useIframe } from "./utils";
import { ref, onMounted, computed } from "vue";
export default {
  components: {
    Form,
  },
  setup() {
    const form = ref(null);
    const interaction = ref({});
    onMounted(async () => {
      let i = await useIframe().getInteraction();
      console.log(i);
      interaction.value = i;
      console.log(interaction.value);
    });

    const close = () => {
      useIframe().close();
    };
    const confirm = () => {
      useIframe().sent();
    };

    const title = computed(() => {
      return interaction.value && interaction.value.form
        ? interaction.value.form.split("/")[
            interaction.value.form.split("/").length - 2
          ]
        : "uContact form";
    });
    return { interaction, title, close, confirm };
  },
};
</script>

<template>
  <div class="header">
    <img contain alt="" src="./assets/icons/uContact.png" width="40" />
    <h2>
      {{ title }}
    </h2>
  </div>
  <Form :interaction="interaction" @close="close" @confirm="confirm" />
</template>

<style>
* {
  margin: 0;
  box-sizing: border-box;
}
html,
body {
  height: 100%;
}
#app {
  height: calc(100% - 4rem);
}
</style>
<style scoped>
.header {
  width: 100%;
  height: 4rem;
  background: #0095ff;
  display: flex;
  align-items: center;
}
.header img {
  margin: 0 10px;
}
.header h2 {
  color: white;
  font-family: "Segoe UI";
  font-weight: 300;
  font-size: 2rem;
}
</style>

// React/src/App.jsx
import { useState, useEffect } from 'react'
import uContactLogo from './assets/icons/uContact.png'
import reactLogo from './assets/icons/react.svg'
import Form from './components/Form'
import './css/header.css'
import { useIframe } from './utils';

function App() {
  const [interaction, setInteraction] = useState({})

  useEffect(() => {
    let init = async () => {
      let i = await useIframe().getInteraction();
      setInteraction({...i});
    }
    init();
  }, []);

  return (
    <>
      <div className="header">
        <img alt="uContactLogo" src={uContactLogo} width="40" />
        <h2 style={{'textAlign': 'center', flex: 1}}>
          {interaction.form ?
            interaction.form.split("/")[
              interaction.form.split("/").length - 2
            ]
            : 'uContact Form'}
        </h2>
        <img
          alt="reactLogo"
          src={reactLogo}
          width="40"
          style={{ marginLeft: 'auto' }}
        />
      </div>
      <Form interaction={interaction} />
    </>
  )
}

export default App
